name: "Deploy to AWS"

on: workflow_dispatch

jobs:
  deploy-AWS:
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v4

      - name: Install packages
        run: npm install

      - name: Test
        run: npm test

      - name: deploy to Aws
        run: pm2 start src/index.js